# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/ja/code-security/dependabot/working-with-dependabot/dependabot-options-reference

version: 2
updates:
  - package-ecosystem: github-actions
    groups:
      github-actions:
        patterns:
          - "*"
    directory: /
    schedule:
      interval: daily
      time: "18:00"
      timezone: "Asia/Tokyo"
    target-branch: develop

  - package-ecosystem: npm
    groups:
      npm:
        patterns:
          - "*"
    directory: /
    schedule:
      interval: daily
      time: "19:00"
      timezone: "Asia/Tokyo"
    target-branch: develop

  - package-ecosystem: pip
    groups:
      pip:
        patterns:
          - "*"
    directory: /
    schedule:
      interval: daily
      time: "20:00"
      timezone: "Asia/Tokyo"
    target-branch: develop

  - package-ecosystem: devcontainers
    directory: /.devcontainer
    schedule:
      interval: daily
      time: "21:00"
      timezone: "Asia/Tokyo"
    target-branch: develop
