name: 'Build by stlite'
description: 'Setup playwright with cache'

inputs:
  github-token:
    description: 'GitHub token'
    required: true

env:
  NODE_OPTIONS: "--max-http-header-size=8192 --max-old-space-size=4096"

runs:
  using: "composite"
  steps:
  - name: Restore cache electron-builder (Windows)
    if: runner.os == 'Windows'
    uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
    with:
      path: |
        %LOCALAPPDATA%\electron\Cache
        %LOCALAPPDATA%\electron-builder\Cache
        %USERPROFILE%\.electron
        %USERPROFILE%\.electron-builder
        ~/AppData/Local/electron/Cache
        ~/AppData/Local/electron-builder/Cache
      key: ${{ runner.os }}-node-electron-builder-${{ hashFiles('**/package-lock.json') }}

  - name: Restore cache electron-builder (MacOS)
    if: runner.os == 'MacOS'
    uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
    with:
      path: |
        ~/Library/Caches/electron
        ~/Library/Caches/electron-builder
        ~/.electron
        ~/.electron-builder
        ~/Library/Caches/electron/
        ~/Library/Caches/electron-builder/
      key: ${{ runner.os }}-node-electron-builder-${{ hashFiles('**/package-lock.json') }}

  - name: Restore cache electron-builder (Linux)
    uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
    if: runner.os == 'Linux'
    with:
      path: |
        ~/.cache/electron
        ~/.cache/electron-builder
        ~/.electron
        ~/.electron-builder
      key: ${{ runner.os }}-node-electron-builder-${{ hashFiles('**/package-lock.json') }}

  - name: Dump package
    # TODO: stliteのWindows環境のビルド失敗が解消したら削除
    if: runner.os == 'MacOS'
    shell: bash
    run: |
      npm run dump

  - name: Set GH_TOKEN
    shell: bash
    run: |
      echo "::add-mask::${{ inputs.github-token }}" && export GH_TOKEN="${{ inputs.github-token }}"

  - name: Build
    # TODO: stliteのWindows環境のビルド失敗が解消したら削除
    if: runner.os == 'MacOS'
    shell: bash
    run: |
      npm run dist

  - name: Upload artifact (Windows)
    uses: actions/upload-artifact@v4.6.2
    if: ${{ runner.os == 'Windows' }}
    with:
      name: ${{ runner.os }}-build-artifact
      path: ./dist/*.exe
      retention-days: 3
      compression-level: 9

  - name: Upload artifact (MacOS)
    uses: actions/upload-artifact@v4.6.2
    if: ${{ runner.os == 'MacOS' }}
    with:
      name: ${{ runner.os }}-build-artifact
      path: ./dist/*.dmg
      retention-days: 3
      compression-level: 9