name: 'Build by stlite'
description: 'Setup playwright with cache'

runs:
  using: "composite"
  steps:
  - name: Restore cache electron-builder (Windows)
    if: runner.os == 'Windows'
    uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
    with:
      path: |
        %LOCALAPPDATA%\electron\Cache
        %LOCALAPPDATA%\electron-builder\Cache
        %USERPROFILE%\.electron
        %USERPROFILE%\.electron-builder
        ~/AppData/Local/electron/Cache
        ~/AppData/Local/electron-builder/Cache
      key: ${{ runner-os }}-node-electron-builder-${{ hashFiles('**/package-lock.json') }}
      restore-keys: |
        ${{ runner-os }}-node-electron-builder-

  - name: Restore cache electron-builder (MacOS)
    if: runner.os == 'MacOS'
    uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
    with:
      path: |
        ~/Library/Caches/electron
        ~/Library/Caches/electron-builder
        ~/.electron
        ~/.electron-builder
        ~/Library/Caches/electron/
        ~/Library/Caches/electron-builder/
      key: ${{ runner-os }}-node-electron-builder-${{ hashFiles('**/package-lock.json') }}
      restore-keys: |
        ${{ runner-os }}-node-electron-builder-

  - name: Restore cache electron-builder (Linux)
    if: runner.os == 'Linux'
    uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
    with:
      path: |
        ~/.cache/electron
        ~/.cache/electron-builder
        ~/.electron
        ~/.electron-builder
      key: ${{ runner-os }}-node-electron-builder-${{ hashFiles('**/package-lock.json') }}
      restore-keys: |
        ${{ runner-os }}-node-electron-builder-

  - name: Dump package
    run: |
      npm run dump
    # TODO: stliteのWindows環境のビルド失敗が解消したら削除
    if: runner.os == 'MacOS'

  - name: Set GH_TOKEN
    run: |
      echo "::add-mask::${{ secrets.GITHUB_TOKEN }}" && export GH_TOKEN="${{ secrets.GITHUB_TOKEN }}"

  - name: Build
    run: |
      npm run dist
    env:
      NODE_OPTIONS: "--max-http-header-size=8192 --max-old-space-size=4096"
    # TODO: stliteのWindows環境のビルド失敗が解消したら削除
    if: runner.os == 'MacOS'

  - name: Upload artifact (Windows)
    uses: actions/upload-artifact@v4.6.2
    with:
      name: ${{ runner.os }}-build-artifact
      path: ./dist/*.exe
      retention-days: 3
      compression-level: 9
    if: ${{ runner.os == 'Windows' }}

  - name: Upload artifact (MacOS)
    uses: actions/upload-artifact@v4.6.2
    with:
      name: ${{ runner.os }}-build-artifact
      path: ./dist/*.dmg
      retention-days: 3
      compression-level: 9
    if: ${{ runner.os == 'MacOS' }}