# Workflow description:
# 1. Restore cached electron-builder dependencies based on OS and package-lock.json.
# 2. Run `npm run dump` (likely related to dependency preparation or configuration).
# 3. Set GITHUB_TOKEN and GH_TOKEN environment variables using the provided input.
# 4. Run `npm run dist` to build the application distribution.
# 5. Upload the built application artifact (`.exe` for Windows, `.dmg` for macOS).
#
# Usage example:
# jobs:
#   build:
#     runs-on: ${{ matrix.os }}
#     strategy:
#       matrix:
#         os: [ubuntu-latest, macos-latest, windows-latest]
#     steps:
#       - uses: actions/checkout@v4
#       # ... other setup steps (e.g., setup-node)
#       - name: Build application
#         uses: ./.github/actions/build-stlite
#         with:
#           github-token: ${{ secrets.GITHUB_TOKEN }} # Required for potentially releasing/uploading
#
---
name: "Build by stlite"
description: "Setup playwright with cache"

inputs:
  github-token:
    description: "GitHub token"
    required: true

runs:
  using: "composite"
  steps:
    - name: Restore cache electron-builder (Windows)
      if: runner.os == 'Windows'
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: |
          %LOCALAPPDATA%\electron\Cache
          %LOCALAPPDATA%\electron-builder\Cache
          %USERPROFILE%\.electron
          %USERPROFILE%\.electron-builder
          ~/AppData/Local/electron/Cache
          ~/AppData/Local/electron-builder/Cache
        key: ${{ runner.os }}-node-electron-builder-${{ hashFiles('**/package-lock.json') }}

    - name: Restore cache electron-builder (MacOS)
      if: runner.os == 'MacOS'
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: |
          ~/Library/Caches/electron
          ~/Library/Caches/electron-builder
          ~/.electron
          ~/.electron-builder
          ~/Library/Caches/electron/
          ~/Library/Caches/electron-builder/
        key: ${{ runner.os }}-node-electron-builder-${{ hashFiles('**/package-lock.json') }}

    - name: Restore cache electron-builder (Linux)
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      if: runner.os == 'Linux'
      with:
        path: |
          ~/.cache/electron
          ~/.cache/electron-builder
          ~/.electron
          ~/.electron-builder
        key: ${{ runner.os }}-node-electron-builder-${{ hashFiles('**/package-lock.json') }}

    - name: Dump package
      shell: bash
      run: |
        npm run dump

    - name: Set GITHUB_TOKEN
      shell: bash
      run: |
        echo "GITHUB_TOKEN=${{ inputs.github-token }}" >> "$GITHUB_ENV"
        echo "GH_TOKEN=${{ inputs.github-token }}" >> "$GITHUB_ENV"

    - name: Build
      shell: bash
      run: |
        npm run dist

    - name: Upload artifact (Windows)
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      if: ${{ runner.os == 'Windows' }}
      with:
        name: ${{ runner.os }}-build-artifact
        path: ./dist/*.exe
        retention-days: 3
        compression-level: 9

    - name: Upload artifact (MacOS)
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      if: ${{ runner.os == 'MacOS' }}
      with:
        name: ${{ runner.os }}-build-artifact
        path: ./dist/*.dmg
        retention-days: 3
        compression-level: 9
