codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: 80%
        threshold: 2%
        if_ci_failed: error
        only_pulls: true
    patch:
      default:
        target: 80%
        threshold: 5%
        if_ci_failed: error
        only_pulls: true

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: true
  require_base: true
  require_head: true

ignore:
  - "tests/"
  - "**/*.md"
  - ".github/"
  - "docs/"
  - "**/conftest.py"
  - "setup.py"
  - "**/__init__.py"

github_checks:
  annotations: true
