[build-system]
build-backend = "poetry.core.masonry.api"

requires = [
  "poetry-core",
]

[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
streamlit = "^1.35.0"
jinja2 = "^3.1.4"
pyyaml = "^6.0.1"

[tool.poetry.group.dev.dependencies]
flake8 = "^7.0.0"
flake8-pyproject = "^1.2.3"
flake8-pytest-style = "^2.0.0"
flake8-builtins = "^2.5.0"
black = "^24.4.2"
isort = "^5.13.2"
mypy = "^1.10.0"
pytest = "^8.2.2"
pytest-cov = "^5.0.0"
types-toml = "^0.10.8.20240310"
pre-commit = "^3.7.1"
lizard = "^1.17.10"
pep8-naming = "^0.14.1"
poetry-types = "^0.5.1"
types-pyyaml = "^6.0.12.20240311"
flake8-bugbear = "^24.4.26"
flake8-annotations = "^3.1.0"
pydeps = "^1.12.20"
pytest-playwright = "^0.5.0"
bandit = "^1.7.8"

[tool.black]
target-version = [
  'py312',
]
line-length = 140

[tool.ruff]
line-length = 140

indent-width = 4

[tool.isort]
line_length = 140

[tool.pytest.ini_options]
testpaths = [
  "tests",
]
pythonpath = "."
addopts = [
  "--import-mode=importlib",
]

[tool.mypy]
python_version = "3.12"
no_strict_optional = true
ignore_missing_imports = false
check_untyped_defs = true

[tool.bandit]
exclude_dirs = [
  ",.github",
  ".venv",
  "node_modules",
  "htmlcov",
  ".mypy_cache",
  ".pytest_cache",
  "__pycache__",
  "tests",
  "build",
  "dist",
]
