name: Create requirements.txt

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      artifact-name:
        required: true
        type: string

jobs:
  create_requirements:
    # https://python-poetry.org/docs/cli/#export
    name: Create requirements.txt
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      REQUIREMENTS_TXT: $GITHUB_WORKSPACE/requirements.txt
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      - name: Bootstrap poetry
        run: |
          curl -sL https://install.python-poetry.org | python - -y
        shell: bash
      - name: Update PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Create a new file
        run: |
          poetry export -f requirements.txt -o "${REQUIREMENTS_TXT}" --without-hashes -v
          echo "# dummy change" >> ${REQUIREMENTS_TXT}
          cat ${REQUIREMENTS_TXT}
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Commit and push changes
        run: |
          git add ${REQUIREMENTS_TXT}
          git commit -m "Add requirements.txt"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Archive requirements.txt
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: |
            ${REQUIREMENTS_TXT}