name: 'Harden Runner'
description: 'Configure step-security/harden-runner with common settings'

runs:
  using: "composite"
  steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
      with:
        egress-policy: audit
        disable-sudo: true
        disable-file-monitoring: false
        allowed-endpoints: |
          api.github.com:443
          github.com:443
          objects.githubusercontent.com:443
          registry.npmjs.org:443
          pypi.org:443
          files.pythonhosted.org:443
          playwright.azureedge.net:443