[global]
hostname = "SAMPLE-ROUTER-001"
vlans = [10, 20, 30, 99]

[global.password]
enable = "P@ssw0rd"

[interfaces."GigabitEthernet0/1"]
mode = "access"
access_vlan = 10
description = "admin office"
cdp_enable = false

[interfaces."GigabitEthernet0/2"]
mode = "access"
access_vlan = 20
description = "accounting office"
cdp_enable = false

[interfaces."GigabitEthernet0/3"]
mode = "access"
access_vlan = 30
description = "engineering office"
cdp_enable = false

[interfaces."GigabitEthernet0/19"]
mode = "trunk"
native_vlan = 99
description = "access point #2"
cdp_enable = true

[interfaces."GigabitEthernet0/20"]
mode = "trunk"
native_vlan = 99
description = "access point #1"
cdp_enable = true

[interfaces."GigabitEthernet0/23"]
mode = "trunk"
description = "uplink #2"
cdp_enable = true

[interfaces."GigabitEthernet0/24"]
mode = "trunk"
description = "uplink #1"
cdp_enable = true
