wan_interface_primary = "wan1"
wan_interface_secondary = "wan2"
lan_interface = "internal"
remote_site_label = "Osaka"
primary_tunnel_name = "vpn-hq-osaka-primary"
secondary_tunnel_name = "vpn-hq-osaka-secondary"
vpn_zone_name = "zone-vpn-osaka"
remote_gateway_primary = "203.0.113.50"
remote_gateway_secondary = "203.0.113.60"
local_subnet = "10.10.0.0/24"
remote_subnet = "10.20.0.0/24"
dpd_mode = "on-idle"
dpd_retryinterval = 5
dpd_retrycount = 3
route_distance_primary = 10
route_distance_secondary = 20
policy_id_out = 31
policy_id_in = 32
policy_name_out = "out_lan-zone-vpn-osaka"
policy_name_in = "in_zone-vpn-osaka-lan"
