vsys_location = "Shared"
signing_ca_name = "ca-internal-issuing-01"
new_cert_name = "cert-gp-gw-hq-2026"
new_cert_common_name = "vpn-hq.example.com"
gp_ssl_profile_name = "sslprofile-gp-gw-hq"
gp_gateway_name = "GW-HQ-External"
gui_ssl_profile_name = "sslprofile-mgmt-gui"
gui_cert_name = "cert-mgmt-gui-2025"
gui_cert_common_name = "fw01-mgmt.example.com"
gui_cert_new_expiration_days = 365
min_tls_version = "TLSv1.3"
max_tls_version = "TLSv1.3"
retired_cert_name = "cert-mgmt-gui-2023"
verification_client_host = "checker01.example.com"
