internal_zone = "trust"
external_zone = "untrust"
sinkhole_zone = "sinkhole"
anti_spyware_profile_name = "AS-C2-Block"
signature_rule_name = "C2-Malware-Signatures"
signature_severity_list = "critical, high, medium"
signature_action = "Reset Both"
packet_capture_mode = "single-packet"
dns_signature_source = "DNS Security"
dns_log_severity = "critical"
dns_policy_action = "sinkhole"
sinkhole_ipv4 = "198.51.100.1"
security_rule_name = "ALLOW-TRUST-TO-UNTRUST-WEB"
infected_host_ip = "192.0.2.45"
test_domain_c2 = "test-c2.testpanw.com"
test_domain_dnstunnel = "test-dnstun.testpanw.com"
test_domain_dga = "test-dga.testpanw.com"
