egress_interface = "ethernet1/1"
interface_egress_max_mbps = 100
qos_profile_name = "QP-WAN-Uplink"
profile_egress_max_mbps = 100
profile_egress_guaranteed_mbps = 90
critical_class_id = 1
critical_class_priority = "real-time"
critical_class_guaranteed_percent = 40
critical_class_guaranteed_effective_mbps = 40
critical_class_max_mbps = 60
noncritical_class_id = 8
noncritical_class_priority = "low"
noncritical_class_guaranteed_percent = 5
noncritical_class_guaranteed_effective_mbps = 5
noncritical_class_max_mbps = 20
critical_rule_name = "QoS-ERP-Critical"
noncritical_rule_name = "QoS-FileTransfer-Limit"
critical_application = "ms-sql-db"
noncritical_application = "ftp"
qos_source_zone = "trust"
qos_destination_zone = "untrust"
congestion_check_source = "10.0.10.50"
