wan_interface = "X1"
wan_zone = "WAN"
lan_interface = "X0"
lan_zone = "LAN"
wan_uplink_mbps = 100
critical_address_object = "N_LAN_ERP_SEGMENT"
critical_address_network = "192.168.10.0"
critical_address_netmask = "255.255.255.0"
critical_bandwidth_object = "BWO_ERP_CRITICAL"
critical_priority = 0
critical_guaranteed_bandwidth = 30
critical_guaranteed_unit = "Mbps"
critical_maximum_bandwidth = 50
critical_maximum_unit = "Mbps"
critical_access_rule_name = "ACC_QOS_ERP_CRITICAL"
noncritical_address_object = "N_LAN_GENERAL_USERS"
noncritical_address_network = "192.168.20.0"
noncritical_address_netmask = "255.255.255.0"
noncritical_bandwidth_object = "BWO_GENERAL_NONCRITICAL"
noncritical_priority = 7
noncritical_guaranteed_bandwidth = 5
noncritical_guaranteed_unit = "Mbps"
noncritical_maximum_bandwidth = 20
noncritical_maximum_unit = "Mbps"
noncritical_access_rule_name = "ACC_QOS_GENERAL_LIMIT"
