name: Lint GitHub Actions workflows

on:
  push:
    branches:
      - main
      - develop
    paths:
      - ".github/workflows/*.yml"
      - ".github/workflows/*.yaml"
  pull_request:
    branches:
      - main
      - develop
    paths:
      - ".github/workflows/*.yml"
      - ".github/workflows/*.yaml"

jobs:
  lint:
    strategy:
      matrix:
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    container:
      image: rhysd/actionlint:latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: Check workflow files
        uses: reviewdog/action-actionlint@v1
