name: Lint GitHub Actions workflows
on:
  push:
    branches:
      - main
      - develop
    paths:
      - ".github/actions/*.yml"
      - ".github/actions/*.yaml"
      - ".github/workflows/*.yml"
      - ".github/workflows/*.yaml"
  pull_request:
    branches:
      - main
      - develop
    paths:
      - ".github/actions/*.yml"
      - ".github/actions/*.yaml"
      - ".github/workflows/*.yml"
      - ".github/workflows/*.yaml"
defaults:
  run:
    shell: bash
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  lint:
    strategy:
      matrix:
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: Check workflow files
        uses: reviewdog/action-actionlint@v1
