---
name: Auto-merge for dependabot

on:
  pull_request:
    branches:
      - develop

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GLOBAL_ALLOWED_ENDPOINTS: |
    api.github.com:443
    github.com:443
  GLOBAL_PYTHON_VERSION: ${{ vars.GLOBAL_PYTHON_VERSION }}

permissions:
  contents: read

jobs:
  detect-dependabot-pr:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    outputs:
      package-ecosystem: ${{ steps.meta.outputs.package-ecosystem }}
      package-name: ${{ steps.meta.outputs.package-name }}
      package-version: ${{ steps.meta.outputs.package-version }}
    permissions:
      contents: write
      pull-requests: write
      checks: read
    steps:
      - name: Harden Runner
        timeout-minutes: 5
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit
          disable-sudo: true
          disable-file-monitoring: false
          allowed-endpoints: |
            api.github.com:443
            github.com:443

      - name: Dependabot metadata
        id: meta
        timeout-minutes: 5
        uses: dependabot/fetch-metadata@d7267f607e9d3fb96fc2fbe83e0af444713e90b7 # v2.3.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

  test-and-build:
    needs:
      - detect-dependabot-pr
    uses: ./.github/workflows/reusable-test-and-build.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    with:
      concurrency_group: push-${{ github.workflow }}-${{ github.ref }}
      concurrency_cancel_in_progress: true
      workflow_summary_name: "Workflow summary [Test & Build (dependabot)]"
