---
name: Auto-merge for dependabot

on:
  pull_request:
    branches:
      - develop

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GLOBAL_ALLOWED_ENDPOINTS: |
    api.github.com:443
    github.com:443
  GLOBAL_PYTHON_VERSION: ${{ vars.GLOBAL_PYTHON_VERSION }}

permissions:
  contents: read

jobs:
  detect-dependabot-pr:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    outputs:
      package-ecosystem: ${{ steps.meta.outputs.package-ecosystem }}
      package-name: ${{ steps.meta.outputs.package-name }}
      package-version: ${{ steps.meta.outputs.package-version }}
    permissions:
      contents: write
      pull-requests: write
      checks: read
    steps:
      - name: Harden Runner
        timeout-minutes: 5
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit
          disable-sudo: true
          disable-file-monitoring: false
          allowed-endpoints: |
            api.github.com:443
            github.com:443

      - name: Dependabot metadata
        id: meta
        timeout-minutes: 5
        uses: dependabot/fetch-metadata@d7267f607e9d3fb96fc2fbe83e0af444713e90b7 # v2.3.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

  test-and-build:
    needs:
      - detect-dependabot-pr
    uses: ./.github/workflows/reusable-test-and-build.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    with:
      concurrency_group: push-${{ github.workflow }}-${{ github.ref }}
      concurrency_cancel_in_progress: true
      workflow_summary_name: "Workflow summary [Test & Build (dependabot)]"

  pyre:
    needs:
      - detect-dependabot-pr
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit
          disable-sudo: true
          disable-file-monitoring: true
          allowed-endpoints: ${{ env.GLOBAL_ALLOWED_ENDPOINTS }}

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 1

      - name: Test Pyre
        uses: ./.github/actions/test-pyre
        with:
          python-version: ${{ env.GLOBAL_PYTHON_VERSION }}
        timeout-minutes: 10
        continue-on-error: true

  merge:
    runs-on: ubuntu-latest
    needs:
      - detect-dependabot-pr
      - test-and-build
    steps:
      - name: Approve and auto-merge
        if: |
          needs.detect-dependabot-pr.outputs.package-ecosystem == 'github-actions' ||
          needs.detect-dependabot-pr.outputs.package-ecosystem == 'pip' ||
          needs.detect-dependabot-pr.outputs.package-ecosystem == 'npm_and_yarn'
        run: |
          gh pr review "$PR_URL" --approve
          gh pr merge --auto --merge "$PR_URL"
        timeout-minutes: 5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
