---
name: Auto-merge for dependabot

on:
  pull_request:
    branches:
      - develop

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  merge:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Dependabot metadata
        id: meta
        uses: dependabot/fetch-metadata@v2

      # GitHub Actions updates - always auto-merge
      - if: ${{ steps.meta.outputs.package-ecosystem == 'github-actions' }}
        run: |
          gh pr review "$PR_URL" --approve
          gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}

      # NPM patch and minor updates - auto-merge
      - if: ${{ steps.meta.outputs.package-ecosystem == 'npm_and_yarn' && (steps.meta.outputs.update-type == 'version-update:semver-patch' || steps.meta.outputs.update-type == 'version-update:semver-minor') }}
        run: |
          gh pr review "$PR_URL" --approve
          gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}

      # Pip patch and minor updates - auto-merge
      - if: ${{ steps.meta.outputs.package-ecosystem == 'pip' && (steps.meta.outputs.update-type == 'version-update:semver-patch' || steps.meta.outputs.update-type == 'version-update:semver-minor') }}
        run: |
          gh pr review "$PR_URL" --approve
          gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
