name: Create PR to main

on:
  workflow_run:
    workflows: ["Test & Build"]
    types:
      - completed
    branches:
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.event.workflow_run.head_branch }}
  cancel-in-progress: true

jobs:
  create-pr:
    runs-on: ubuntu-latest
    # 明示的にタイムアウトを設定
    timeout-minutes: 10
    # テスト成功時のみ実行
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'develop'
    # 必要最小限の権限のみを付与
    permissions:
      contents: read
      pull-requests: write
    steps:
      # デバッグログの強化
      - name: Dump GitHub context
        id: github_context_step
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT" | jq -r '. | {event_name, workflow_ref, repository, run_id, run_number}'

      - uses: actions/checkout@v4
        with:
          ref: develop
          fetch-depth: 0
          # 明示的にトークンを渡す（セキュリティのため）
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check version change
        id: check-version
        # シェルスクリプトを安全モードで実行
        shell: bash
        run: |
          set -euo pipefail

          # package.json を変更した最新のコミットハッシュを取得
          latest_commit=$(git log -1 --pretty=format:"%H" -- package.json || echo "")

          if [ -z "$latest_commit" ]; then
            echo "::notice::package.json の変更が見つかりません"
            echo "version_changed=false" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          # ファイルが存在するか確認
          if [ ! -f "package.json" ]; then
            echo "::error::package.json ファイルが見つかりません"
            echo "version_changed=false" >> "$GITHUB_OUTPUT"
            exit 1
          fi

          # 変更前のバージョンを取得
          if ! old_version=$(git show "$latest_commit^:package.json" | jq -r '.version' 2>/dev/null); then
            echo "::warning::古いバージョンの取得に失敗しました"
            echo "version_changed=false" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          # 現在のバージョンを取得
          if ! current_version=$(jq -r '.version' package.json 2>/dev/null); then
            echo "::error::現在のバージョンの取得に失敗しました"
            echo "version_changed=false" >> "$GITHUB_OUTPUT"
            exit 1
          fi

          # バージョン形式の簡易検証（セマンティックバージョニング）
          if ! [[ $current_version =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?(\+[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?$ ]]; then
            echo "::warning::バージョン形式が正しくありません: $current_version"
          fi

          if [ "$old_version" != "$current_version" ]; then
            echo "::notice::バージョンが $old_version から $current_version に変更されました"
            echo "version_changed=true" >> "$GITHUB_OUTPUT"
            echo "new_version=$current_version" >> "$GITHUB_OUTPUT"
            echo "old_version=$old_version" >> "$GITHUB_OUTPUT"
          else
            echo "::notice::バージョンに変更はありません"
            echo "version_changed=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Check if PR already exists
        id: check-pr
        if: steps.check-version.outputs.version_changed == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          set -euo pipefail

          echo "::notice::既存のPRを確認中..."
          if ! pr_exists=$(gh pr list \
            --head develop \
            --base main \
            --state open \
            --json number \
            --jq length); then
            echo "::error::PRの一覧取得に失敗しました"
            echo "exists=error" >> "$GITHUB_OUTPUT"
            exit 1
          fi

          echo "::notice::既存のオープンPR: $pr_exists"
          echo "exists=$pr_exists" >> "$GITHUB_OUTPUT"

      # ラベルの存在確認と作成
      - name: Ensure labels exist
        id: ensure-labels
        if: |
          steps.check-version.outputs.version_changed == 'true' &&
          steps.check-pr.outputs.exists == '0'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          set -euo pipefail

          echo "::notice::ラベルの確認中..."

          # リポジトリの既存ラベルを取得
          if ! labels=$(gh label list --json name --jq '.[].name'); then
            echo "::warning::ラベル一覧の取得に失敗しました"
            # 続行可能なエラーなので失敗としない
          fi

          # automated-pr ラベルがなければ作成
          if ! echo "$labels" | grep -q "automated-pr"; then
            echo "::notice::ラベル 'automated-pr' を作成します"
            if ! gh label create "automated-pr" --description "自動生成されたPR" --color "0E8A16"; then
              echo "::warning::ラベル 'automated-pr' の作成に失敗しました"
            else
              echo "automated_pr_created=true" >> "$GITHUB_OUTPUT"
            fi
          else
            echo "automated_pr_exists=true" >> "$GITHUB_OUTPUT"
          fi

          # release ラベルがなければ作成
          if ! echo "$labels" | grep -q "release"; then
            echo "::notice::ラベル 'release' を作成します"
            if ! gh label create "release" --description "自動リリース用PR" --color "1D76DB"; then
              echo "::warning::ラベル 'release' の作成に失敗しました"
            else
              echo "release_created=true" >> "$GITHUB_OUTPUT"
            fi
          else
            echo "release_exists=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Create Pull Request
        id: create-pr
        if: |
          steps.check-version.outputs.version_changed == 'true' &&
          steps.check-pr.outputs.exists == '0'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          set -euo pipefail

          echo "::notice::PRの作成準備中..."

          # develop ブランチから最新のコミットメッセージを取得
          if ! commit_msg=$(git log -1 --pretty=%B); then
            echo "::warning::コミットメッセージの取得に失敗しました"
            commit_msg="(コミットメッセージを取得できませんでした)"
          fi

          # 機密情報や個人情報が含まれていないか確認（簡易的）
          if echo "$commit_msg" | grep -iE '(password|secret|token|key|認証|パスワード)'; then
            echo "::warning::コミットメッセージに機密情報が含まれている可能性があります"
            commit_msg="(セキュリティ上の理由でコミットメッセージを省略しました)"
          fi

          new_version="${{ steps.check-version.outputs.new_version }}"
          old_version="${{ steps.check-version.outputs.old_version }}"

          # PR タイトルを作成
          pr_title="Release v$new_version"

          echo "::notice::コミット一覧を取得中..."
          # main ブランチにまだ取り込まれていないコミットの件名を取得
          # main ブランチをフェッチ
          if ! git fetch origin main:main; then
            echo "::warning::main ブランチのフェッチに失敗しました"
            commit_titles="(コミット一覧を取得できませんでした)"
          else
            # コミット件名のリストを作成（セキュリティのためコミット数に制限）
            if ! commit_titles=$(git log main..develop --max-count=50 --pretty=format:"- %s"); then
              echo "::warning::コミット一覧の取得に失敗しました"
              commit_titles="(コミット一覧を取得できませんでした)"
            fi

            # コミット数が多すぎる場合は警告
            commit_count=$(echo "$commit_titles" | wc -l)
            if [ "$commit_count" -gt 50 ]; then
              echo "::warning::コミット数が多すぎます: $commit_count 件（最初の50件のみ表示）"
              commit_titles="$commit_titles\n\n... 及びその他 $(($commit_count - 50)) 件のコミット"
            fi
          fi

          # PR 本文を作成
          pr_body="develop から main へのバージョン $new_version の自動 PR

          このPRは以下の理由で自動的に作成されました:
          1. develop ブランチ上ですべてのテストが合格
          2. パッケージバージョンが v$old_version から v$new_version に更新された

          コミットメッセージ:
          \`\`\`
          $commit_msg
          \`\`\`

          ## 変更概要
          このPRには、以下のコミットが含まれています:

          $commit_titles

          ## チェック項目
          - [x] すべてのテストが合格
          - [x] コード品質チェックが合格
          - [x] バージョンが v$new_version に更新されました"

          echo "::notice::PRを作成中..."
          # PRを作成
          pr_url=$(gh pr create \
            --base main \
            --head develop \
            --title "$pr_title" \
            --body "$pr_body" \
            --label "automated-pr,release" || echo "")

          if [ -z "$pr_url" ]; then
            echo "::error::PRの作成に失敗しました"
            exit 1
          else
            echo "::notice::PRが作成されました: $pr_url"
            echo "pr_url=$pr_url" >> "$GITHUB_OUTPUT"
          fi

      # 結果の通知
      - name: Notify result
        if: always()
        run: |
          if [[ "${{ steps.create-pr.outcome }}" == "success" && "${{ steps.create-pr.outputs.pr_url }}" != "" ]]; then
            echo "::notice::PR作成成功: ${{ steps.create-pr.outputs.pr_url }}"
          elif [[ "${{ steps.check-version.outputs.version_changed }}" == "false" ]]; then
            echo "::notice::バージョン変更なし - PRは作成されませんでした"
          elif [[ "${{ steps.check-pr.outputs.exists }}" != "0" ]]; then
            echo "::notice::既存のPRが見つかりました - 新規PRは作成されませんでした"
          else
            echo "::warning::PRの作成に問題が発生しました - ワークフロー実行詳細を確認してください"
          fi
