name: Create Release Tag

on:
  pull_request:
    types:
      - closed
    branches:
      - main

permissions:
  contents: read

jobs:
  create-tag:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'release')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          ref: main

      - name: Get version from package.json
        id: get-version
        run: |
          version=$(jq -r '.version' package.json)
          echo "version=$version" >> "$GITHUB_OUTPUT"

      - name: Create and push tag
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          version="${{ steps.get-version.outputs.version }}"
          tag_name="v$version"

          # Check if tag already exists
          if ! git rev-parse "$tag_name" >/dev/null 2>&1; then
            # Create annotated tag
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git tag -a "$tag_name" -m "Release $tag_name"
            git push origin "$tag_name"

            # Create GitHub Release
            gh release create "$tag_name" \
              --title "Release $tag_name" \
              --notes "$(git log --format=%B -n 1 ${{ github.sha }})" \
              --draft=false \
              --prerelease=false

            echo "Created and pushed tag: $tag_name"
          else
            echo "Tag $tag_name already exists"
          fi
