name: Test, Build, and Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      shell: bash
      run: |
        poetry install

    - name: Run mypy
      run: |
        . .venv/bin/activate
        cd packages/kernel/py/stlite-server
        poetry run mypy .

    - name: Run pytest
      run: |
        . .venv/bin/activate
        poetry run pytest