name: Release to Streamlit Cloud

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Create streamlitcloud branch
        run: |
          git checkout -b streamlitcloud
          git push origin streamlitcloud

      - name: Generate requirements.txt from pyproject.toml
        run: |
          poetry export -f requirements.txt --output requirements.txt --without-hashes || {
            echo "::error::requirements.txtの生成に失敗しました"
            exit 1
          }

      - name: Commit and push requirements.txt
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add requirements.txt
          git commit -m "Update requirements.txt from pyproject.toml" || {
            echo "::warning::変更がありませんでした。コミットをスキップします。"
            exit 0
          }
          echo "${{ secrets.GITHUB_TOKEN }}" | git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} streamlitcloud
