# コードにハッシュ検証ポリシーを追加
# SECURITY NOTE FOR REVIEWERS:
# All external actions in this workflow are pinned to specific versions.
# We use either:
# 1. Verified tags (vX.Y.Z) from trusted publishers
# 2. Specific commit SHAs when tags are not preferred
#
# When updating any action, always:
# - Check for security advisories for the action
# - Verify the publisher's reputation
# - Test the new version in a controlled environment first
# - Update this policy comment with any changes
---
name: Reusable Test & Build

on:
  workflow_call:
    inputs:
      concurrency_group:
        required: true
        type: string
      concurrency_cancel_in_progress:
        required: true
        type: boolean
      workflow_summary_name:
        required: true
        type: string
    outputs:
      build_succeeded:
        description: "Whether the build succeeded"
        value: ${{ jobs.workflow-summary.outputs.build_succeeded }}
    secrets:
      CODECOV_TOKEN:
        required: true
      GITHUB_TOKEN:
        required: true

defaults:
  run:
    shell: bash

env:
  GLOBAL_ALLOWED_ENDPOINTS: |
    api.github.com:443
    github.com:443
    objects.githubusercontent.com:443
    registry.npmjs.org:443
    pypi.org:443
    files.pythonhosted.org:443
    playwright.azureedge.net:443
  GLOBAL_NODE_VERSION: ${{ vars.GLOBAL_NODE_VERSION }}
  GLOBAL_PYTHON_VERSION: ${{ vars.GLOBAL_PYTHON_VERSION }}
  ALL_FETCH_DEPTH: 0
  LIZARD_CCN_COUNT: 10

concurrency:
  group: ${{ inputs.concurrency_group }}
  cancel-in-progress: ${{ inputs.concurrency_cancel_in_progress }}

jobs:
  # ============================================================
  # GUARD CLAUSE GROUP
  # ============================================================

  guard-workflow:
    name: Guard workflow files
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit
          disable-sudo: true
          disable-file-monitoring: true
          allowed-endpoints: ${{ env.GLOBAL_ALLOWED_ENDPOINTS }}

      - name: Check out Git repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 1

      - name: Lint yaml files by yamllint
        run: |
          CONFIG="${RUNNER_TEMP}/.yamllint.yml"
          cat <<EOF >"${CONFIG}"
          extends: default
          rules:
            document-start: disable
            truthy:
              allowed-values: ["true", "false", "on"]
            comments:
              min-spaces-from-content: 1
            braces:
              max-spaces-inside: 1
            line-length:
              max: 250
          EOF
          if [ -e ".yamllint.yml" ]; then
            CONFIG=".yamllint.yml"
          fi
          yamllint --strict --format github --config-file "${CONFIG}" ./.github/

      - name: Download and run actionlint
        run: |
          # バイナリのダウンロードとインストール
          curl -sSLo actionlint.bash https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash
          # ダウンロードしたバッシュスクリプトに実行権限を与えて実行
          chmod +x actionlint.bash
          ./actionlint.bash
          # actionlintを実行
          ./actionlint -color

      - name: Check typos
        uses: crate-ci/typos@b1a1ef3893ff35ade0cfa71523852a49bfd05d19 # v1.31.1

  guard-api-key:
    name: Guard API Key
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit
          disable-sudo: true
          disable-file-monitoring: true

      - name: Check out Git repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: ALL_FETCH_DEPTH

      - name: Set GITHUB_TOKEN
        run: |
          echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> "$GITHUB_ENV"

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@83373cf2f8c4db6e24b41c1a9b086bb9619e9cd3 # v2.3.7

      - name: Convert SARIF to Markdown Summary
        uses: ./.github/actions/convert-sarif-to-summary
        with:
          sarif-path: results.sarif
          summary-title: "Gitleaks Analysis Results"

  guard-python:
    name: Guard Python
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit
          disable-sudo: true
          disable-file-monitoring: true
          allowed-endpoints: ${{ env.GLOBAL_ALLOWED_ENDPOINTS }}

      - name: Check out Git repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Python and restore cache
        uses: ./.github/actions/setup-python
        with:
          python-version: ${{ env.GLOBAL_PYTHON_VERSION }}
        timeout-minutes: 10

      - name: Lint Python and check types
        run: |
          poetry run ruff check .
          poetry run mypy .

      - name: Run Trivy vulnerability scan
        uses: aquasecurity/trivy-action@6c175e9c4083a92bbca2f9724c8a5e33bc2d97a5
        with:
          scan-type: "fs"
          ignore-unfixed: true
          format: "table"

  guard-npm:
    name: Guard NPM
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit
          disable-sudo: true
          disable-file-monitoring: true
          allowed-endpoints: ${{ env.GLOBAL_ALLOWED_ENDPOINTS }}

      - name: Check out Git repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 1

      - name: Setup Node.js and restore cache
        uses: ./.github/actions/setup-node
        with:
          node-version: ${{ env.GLOBAL_NODE_VERSION }}
        timeout-minutes: 10

      - name: NPM Audit
        run: |
          # npm auditを実行 (高リスクの脆弱性のみ失敗とする)
          echo "### NPM Audit Results" >> "$GITHUB_STEP_SUMMARY"
          npm audit --production --audit-level=high || {
            echo "::warning::High severity vulnerabilities found in production dependencies"
            echo "⚠️ High severity vulnerabilities found in production dependencies" >> "$GITHUB_STEP_SUMMARY"
            npm audit --production --audit-level=high >> "$GITHUB_STEP_SUMMARY"
          }

  # ============================================================
  # TESTS GROUP
  # ============================================================

  small-unit-test:
    name: Small Unit Tests
    needs:
      - guard-workflow
      - guard-api-key
      - guard-python
      - guard-npm
    permissions:
      contents: read
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        python-version:
          - "3.13"
          - "3.12"
          - "3.11"
    timeout-minutes: 5

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit
          disable-sudo: true
          disable-file-monitoring: true
          allowed-endpoints: ${{ env.GLOBAL_ALLOWED_ENDPOINTS }}

      - name: Check out Git repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 1

      - name: Setup Python and restore cache
        uses: ./.github/actions/setup-python
        with:
          python-version: ${{ env.GLOBAL_PYTHON_VERSION }}
        timeout-minutes: 10

      - name: Run Unit Tests
        run: |
          # 通常のテスト実行 (カバレッジ有、ベンチマークなし)
          cmd_array=(
            poetry run pytest -n auto
            --cov=app.py
            --cov=features
            --cov=i18n
            --cov=scripts
            --cov-report=xml
            --cov-report=term
            --dist loadfile
            --durations=10
            --cache-clear
            --maxfail=5
            --verbose -k 'not e2e'
            --benchmark-disable
          )
          "${cmd_array[@]}"

  test-coverage:
    name: Coverage
    needs: small-unit-test
    permissions:
      contents: read
      checks: write
      id-token: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch:
          - main
          - develop
    timeout-minutes: 5

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit
          disable-sudo: true
          disable-file-monitoring: true
          allowed-endpoints: ${{ env.GLOBAL_ALLOWED_ENDPOINTS }}

      - name: Check out Git repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 1
          ref: ${{ matrix.branch }}

      - name: Setup Python and restore cache
        uses: ./.github/actions/setup-python
        with:
          python-version: ${{ env.GLOBAL_PYTHON_VERSION }}

      - name: Run pytest (coverage without e2e)
        shell: bash
        run: |
          cmd_array=(
            poetry run pytest
            --benchmark-disable
            --cov=app.py
            --cov=features
            --cov=i18n
            --cov=scripts
            --cov-report=xml
            --cov-report=term
            --dist loadfile
            --junitxml=junit.xml
            -n auto
            -k "not e2e"
            -o junit_family=legacy
          )
          "${cmd_array[@]}"

      - name: Upload test results to Codecov
        uses: codecov/test-results-action@f2dba722c67b86c6caa034178c6e4d35335f6706 # v1.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@0565863a31f2c772f9f0395002a31e3f06189574 # v5.4.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

  test-e2e:
    name: E2E Tests (${{ matrix.os }} & ${{ matrix.browser }})
    needs: small-unit-test
    permissions:
      contents: read
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - windows-latest
        browser:
          - chromium
          - firefox
          - webkit
        exclude:
          # WindowsとWebkitの組み合わせを除外
          - os: windows-latest
            browser: webkit
      max-parallel: 10

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit
          disable-sudo: false
          disable-file-monitoring: true
          allowed-endpoints: ${{ env.GLOBAL_ALLOWED_ENDPOINTS }}
        timeout-minutes: 5

      - name: Check out Git repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 1
        timeout-minutes: 3

      - name: Setup Python and restore cache
        uses: ./.github/actions/setup-python
        with:
          python-version: ${{ env.GLOBAL_PYTHON_VERSION }}
        timeout-minutes: 10

      - name: Run E2E Tests (Playwright)
        uses: ./.github/actions/test-python-playwright
        with:
          browser: ${{ matrix.browser }}
        timeout-minutes: 10

  # ============================================================
  # ANALYSIS GROUP
  # ============================================================

  # https://github.com/terryyin/lizard
  analysis-code-ccn:
    name: Code Complexity
    needs: small-unit-test
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit
          disable-sudo: true
          disable-file-monitoring: true
          allowed-endpoints: ${{ env.GLOBAL_ALLOWED_ENDPOINTS }}

      - name: Check out Git repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 1

      - name: Setup Python and restore cache
        uses: ./.github/actions/setup-python
        with:
          python-version: ${{ env.GLOBAL_PYTHON_VERSION }}
        timeout-minutes: 10

      - name: Run lizard (analyze CCN for production codes)
        run: |
          cmd_array=(
            poetry run lizard
            -x './node_modules/*'
            -x './.venv/*'
            -x './build/*'
            -x './dist/*'
            -x './htmlcov/*'
            -x './tests/*'
            --CCN "${LIZARD_CCN_COUNT}" # Quote variable expansion for safety
          )
          "${cmd_array[@]}"

      - name: Show AST (app.py)
        run: |
          python <<EOF
          import ast
          print(ast.dump(ast.parse(open("app.py").read()), indent=2))
          EOF

      - name: Show AST (features/*.py)
        run: |
          python <<EOF
          import ast
          import os
          import pprint
          target_dir = "./features"
          ast_trees = {}
          for file in os.listdir(target_dir):
              if file.endswith(".py"):
                  ast_trees[file] = ast.dump(ast.parse(open(os.path.join(target_dir, file)).read()), indent=2)
          pprint.pprint(ast_trees, width=100, compact=False)
          EOF

  # ============================================================
  # BUILD GROUP
  # ============================================================

  build-desktop:
    name: Build desktop app (${{ matrix.os }})
    needs: small-unit-test
    continue-on-error: ${{ matrix.os == 'windows-latest' }}
    permissions:
      contents: read
      security-events: write
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - windows-latest
    timeout-minutes: 10

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit
          disable-sudo: true
          disable-file-monitoring: true
          allowed-endpoints: ${{ env.GLOBAL_ALLOWED_ENDPOINTS }}

      - name: Check out Git repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 1

      - name: Setup Node.js and cache
        uses: ./.github/actions/setup-node
        with:
          node-version: ${{ env.GLOBAL_NODE_VERSION }}
        timeout-minutes: 10

      - name: Build by stlite
        uses: ./.github/actions/build-stlite
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  # ============================================================
  # WORKFLOW SUMMARY
  # ============================================================

  workflow-summary:
    name: ${{ inputs.workflow_summary_name }}
    if: always()
    needs: [test-coverage, test-e2e, analysis-code-ccn, build-desktop]
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      build_succeeded: ${{ steps.set-result.outputs.build_succeeded }}

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit
          disable-sudo: true
          disable-file-monitoring: true
          allowed-endpoints: ${{ env.GLOBAL_ALLOWED_ENDPOINTS }}

      - id: set-result
        run: |
          {
            # 総合結果の表示
            echo ""
            echo "## 総合結果"

            # いずれかのジョブが失敗した場合に失敗とする
            if [[ "${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}" == "true" ]]; then
              echo "⚠️ **一部のジョブが失敗しました。詳細を確認してください。**"
              echo "build_succeeded=false" >> "$GITHUB_OUTPUT"
            else
              echo "✅ **すべてのジョブが正常に完了しました**"
              echo "build_succeeded=true" >> "$GITHUB_OUTPUT"
            fi
          } >> "$GITHUB_STEP_SUMMARY"

          # ワークフロー全体の結果を設定 - いずれかのジョブが失敗した場合に失敗とする
          if [[ "${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}" == "true" ]]; then
            echo "Some jobs have failed. See the summary for details."
            exit 1
          fi
