name: Reusable Pip Cache
on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      os:
        required: true
        type: string

jobs:
  setup-python-and-cache:
    runs-on: ${{ inputs.os }}
    steps:
      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@19e4675e06535f6b54e894da5c1f044400bb4996 # v5.1.0
        with:
          python-version: ${{ inputs.python-version }}

      - name: Restore cache pip dependencies
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: |
            ~/.cache/pypoetry
            ~/.cache/pip
            .venv
            %LOCALAPPDATA%\pypoetry\Cache
            %USERPROFILE%\.cache\pypoetry
          key: ${{ inputs.os }}-python${{ inputs.python-version }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ inputs.os }}-python${{ inputs.python-version }}-poetry

      - name: Bootstrap poetry
        run: |
          curl -sL https://install.python-poetry.org | python - -y
        shell: bash

      - name: Update PATH
        run: echo "$HOME/.local/bin" >> "$GITHUB_PATH"
        shell: bash

      - name: Configure poetry
        run: poetry config virtualenvs.in-project false
        shell: bash

      - name: Install dependencies
        shell: bash
        run: |
          poetry install --no-interaction --no-root --only main,dev
