---
name: Test & Build (on push)

on:
  push:
    branches:
      - develop
      - main
    paths-ignore:
      - .cursor/**
      - .devcontainer/**
      - assets/**
      - README.md
      - .gitignore
      - .cz_config.js
      - .pre-commit-config.yaml
      - "**.code-workspace"

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  main:
    uses: ./.github/workflows/reusable-test-and-build.yml
    with:
      concurrency_group: push-${{ github.workflow }}-${{ github.ref }}
      concurrency_cancel_in_progress: true
      workflow_summary_name: "Workflow summary [Test & Build (on Push)]"

  create-pr-to-main:
    uses: ./.github/workflows/reusable-create-pr.yml
    if: |
      github.event.ref == 'refs/heads/develop'
    needs: main
    permissions:
      contents: read
      pull-requests: write

  release:
    uses: ./.github/workflows/reusable-release.yml
    if: |
      github.event.ref == 'refs/heads/main'
    needs: main
    with:
      build_succeeded: ${{ needs.main.outputs.build_succeeded }}
    permissions:
      contents: read
      pull-requests: write
    secrets: inherit
