---
name: Test & Build (on merged to main)

on:
  pull_request:
    types:
      - closed
    branches:
      - main

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  main:
    uses: ./.github/workflows/reusable-test-and-build.yml
    with:
      concurrency_group: push-${{ github.workflow }}-${{ github.ref }}
      concurrency_cancel_in_progress: true
      workflow_summary_name: "Workflow summary [Test & Build (on Push)]"

  release:
    uses: ./.github/workflows/reusable-release.yml
    needs: main
    with:
      build_succeeded: ${{ needs.main.outputs.build_succeeded }}
    permissions:
      contents: read
      pull-requests: write
    secrets: inherit
