---
name: Test and Build (on merged to main)

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

env:
  HARDEN_RUNNER_EGRESS_POLICY: audit

permissions:
  actions: read
  contents: read
  checks: write
  id-token: write
  issues: write
  security-events: write

jobs:
  test-and-build:
    uses: ./.github/workflows/reusable-test-and-build.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    with:
      concurrency_group: push-${{ github.workflow }}-${{ github.ref }}
      concurrency_cancel_in_progress: true
      workflow_summary_name: "Workflow summary [Test & Build (main)]"

  create-tag-and-release:
    needs:
      - test-and-build
    outputs:
      tag_name: ${{ steps.set_tag_output.outputs.tag_name }}
      commit_sha: ${{ steps.get_commit_sha.outputs.sha }}
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: ${{ env.HARDEN_RUNNER_EGRESS_POLICY }}
          disable-sudo: true
          disable-file-monitoring: true

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 1

      - name: Get version from main
        id: get-main-ver
        uses: martinbeentjes/npm-get-version-action@3cf273023a0dda27efcd3164bdfb51908dd46a5b # v1.3.1

      - name: Set tag_name output
        id: set_tag_output
        run: echo "tag_name=v${{ steps.get-main-ver.outputs.current-version }}" >> "$GITHUB_OUTPUT"

      - name: Get commit SHA
        id: get_commit_sha
        run: echo "sha=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"

      - name: Download macOS build artifact
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: desktop-app-macOS.zip
          path: artifacts/macos

      - name: Download Windows build artifact
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: desktop-app-Windows.zip
          path: artifacts/windows

      - name: Create Release with Artifacts
        id: create_release # Add an ID for potential future use
        uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631 # v2.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Explicitly pass token
        with:
          tag_name: ${{ steps.set_tag_output.outputs.tag_name }}
          generate_release_notes: true
          target_commitish: ${{ steps.get_commit_sha.outputs.sha }}
          files: |
            artifacts/macos/*.zip
            artifacts/windows/*.zip
          draft: false
          prerelease: false
