---
name: Test & Build (on pull request)

on:
  pull_request:
    branches:
      - main
      - develop
    paths-ignore:
      - .cursor/**
      - .devcontainer/**
      - assets/**
      - README.md
      - .gitignore
      - .cz_config.js
      - .pre-commit-config.yaml
      - "**.code-workspace"
    types:
      - opened
      - synchronize
      - reopened
      - edited

permissions:
  actions: read
  contents: read
  id-token: write
  pull-requests: write
  security-events: write

env:
  GLOBAL_ALLOWED_ENDPOINTS: |
    api.github.com:443
    github.com:443
  GLOBAL_PYTHON_VERSION: ${{ vars.GLOBAL_PYTHON_VERSION }}

jobs:
  main:
    uses: ./.github/workflows/reusable-test-and-build.yml
    with:
      concurrency_group: pr-${{ github.workflow }}-${{ github.ref }}
      concurrency_cancel_in_progress: false
      workflow_summary_name: "Workflow summary [Test & Build (on Pull request)]"

  test-e2e-benchmark:
    name: E2E Benchmark (${{ matrix.os }})
    needs: main
    permissions:
      contents: read
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - windows-latest
        browser:
          - chromium
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit
          disable-sudo: false
          disable-file-monitoring: false
          allowed-endpoints: ${{ env.GLOBAL_ALLOWED_ENDPOINTS }}
        timeout-minutes: 5

      - name: Check out Git repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 1
        timeout-minutes: 3

      - name: Setup Python and restore cache
        uses: ./.github/actions/setup-python
        with:
          python-version: ${{ env.GLOBAL_PYTHON_VERSION }}
        timeout-minutes: 10

      - name: Run E2E Benchmark (Playwright)
        uses: ./.github/actions/test-python-playwright
        with:
          browser: ${{ matrix.browser }}
          is-benchmark: true
        timeout-minutes: 30

  scorecards:
    name: OpenSSF Scorecards
    if: |
      github.event.pull_request.base.ref == 'main'
    permissions:
      contents: read
      actions: read
      security-events: write
      id-token: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit
          disable-sudo: true
          disable-file-monitoring: false
          allowed-endpoints: ${{ env.GLOBAL_ALLOWED_ENDPOINTS }}

      - name: "Checkout code"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: "Run analysis"
        uses: ossf/scorecard-action@f49aabe0b5af0936a0987cfb85d86b75731b0186 # v2.4.1
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true

  dependency-review:
    name: Dependency Review
    permissions:
      contents: read
      pull-requests: write
      actions: read
      security-events: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit
          disable-sudo: true
          disable-file-monitoring: false
          allowed-endpoints: ${{ env.GLOBAL_ALLOWED_ENDPOINTS }}

      - name: Check out Git repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 1

      - name: Dependency Review
        uses: actions/dependency-review-action@ce3cf9537a52e8119d91fd484ab5b8a807627bf8 # v4.6.0
        with:
          fail-on-severity: high
          comment-summary-in-pr: true
          # Pull Requestのコンテキストからbase_refとhead_refを取得
          base-ref: ${{ github.event.pull_request.base.ref }}
          head-ref: ${{ github.event.pull_request.head.ref }}

  pyre:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit
          disable-sudo: true
          disable-file-monitoring: false

      - uses: actions/checkout@v4

      - name: Setup Python and restore cache
        uses: ./.github/actions/setup-python
        with:
          python-version: ${{ env.GLOBAL_PYTHON_VERSION }}
        timeout-minutes: 10

      - name: Create requirements.txt
        run: |
          poetry --version
          poetry config virtualenvs.in-project true
          poetry export -f requirements.txt --output requirements.txt

      - name: Run Pyre Action
        uses: facebook/pyre-action@v0.0.2
        with:
          repo-directory: "./"
          requirements-path: "requirements.txt"
        timeout-minutes: 120
