# ============================================================
# Workflow Information: test-and-build-on-pr.yml
# ============================================================
#
# ワークフローの目的 (Purpose):
# -----------------------------
# main または develop ブランチに対する Pull Request (オープン、同期、再オープン、編集)
# をトリガーとして実行されます。PR のコードに対してテスト、ビルド、ベンチマーク、
# および追加のセキュリティチェック (OSS Scorecards, Dependency Review) を実行します。
# Dependabot による PR の場合、テストが成功すれば自動的に承認します。
#
# ワークフローの影響範囲 (Scope of Impact):
# ---------------------------------------
# - main および develop ブランチへのマージ前のコード品質を検証します。
# - Pull Request にテスト結果、ベンチマーク結果、セキュリティレビュー結果をコメントとして投稿する可能性があります。
# - Dependabot PR を自動承認することがあります。
# - OpenSSF Scorecards の結果を Security タブにアップロードします。
#
# 依存する外部のワークフロー (External Dependencies):
# ------------------------------------------------
# - ./.github/workflows/reusable-test-and-build.yml (テストとビルドのコアロジック)
# - 複数の外部 GitHub Actions (Harden Runner, Checkout, Setup Python, Test Playwright, Scorecard, Dependency Review, Fetch Metadata, gh CLI など)
#
# セキュリティポリシー (Security Policy):
# ------------------------------------
# - `permissions` キーでワークフローの権限を最小限に制限しています (PR コメント、Dependabot 承認、Scorecards 結果アップロードのため write 権限を含む)。
# - `step-security/harden-runner` を使用してランナーのセキュリティを強化しています (egress-policy: audit)。
# - OpenSSF Scorecards によるセキュリティベストプラクティスの評価を実施します。
# - Dependency Review Action により、PR で導入される依存関係の脆弱性をチェックします。
# - Dependabot PR の自動承認は、テストジョブ (`test-and-build`) の成功を条件とします。
#
# 参考URL (Reference URLs):
# -------------------------
# - GitHub Actions Documentation: https://docs.github.com/ja/actions
# - Reusable Workflow: ./.github/workflows/reusable-test-and-build.yml
# - OpenSSF Scorecards: https://github.com/ossf/scorecard
# - Dependency Review Action: https://github.com/actions/dependency-review-action
# - Dependabot: https://docs.github.com/ja/code-security/dependabot
#
# ============================================================
---
name: Test and Build - on pull request

on:
  pull_request:
    branches:
      - main
      - develop
    paths-ignore:
      - .cursor/**
      - .devcontainer/**
      - assets/**
      - docs/**
      - .gitignore
      - .pre-commit-config.yaml
      - .watchmanconfig
      - .yamllint.yml
      - "**.code-workspace"
      - commitlint.config.js
      - LICENSE
      - README.md
    types:
      - opened
      - synchronize
      - reopened
      - edited

permissions:
  actions: write
  contents: write
  checks: write
  id-token: write
  issues: write
  security-events: write

env:
  HARDEN_RUNNER_EGRESS_POLICY: audit

jobs:
  test-and-build:
    uses: ./.github/workflows/reusable-test-and-build.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    with:
      concurrency_group: pr-${{ github.workflow }}-${{ github.event.pull_request.number }}
      concurrency_cancel_in_progress: true
      workflow_summary_name: "Workflow summary [Test & Build (on pull request)]"

  dependency-review:
    name: Dependency Review
    if: github.event_name == 'pull_request'
    permissions:
      actions: read
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: ${{ env.HARDEN_RUNNER_EGRESS_POLICY }}
          disable-sudo: true
          allowed-endpoints: >
            api.github.com:443
            github.com:443

      - name: Check out Git repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 1

      - name: Dependency Review
        uses: actions/dependency-review-action@da24556b548a50705dd671f47852072ea4c105d9 # v4.7.1
        with:
          fail-on-severity: high
          comment-summary-in-pr: true
          # Pull Requestのコンテキストからbase_refとhead_refを取得
          base-ref: ${{ github.event.pull_request.base.ref }}
          head-ref: ${{ github.event.pull_request.head.ref }}

  auto-approve-dependabot-pr:
    name: Auto-approve Dependabot pull request
    if: |
      github.actor == 'dependabot[bot]' &&
      startsWith(github.head_ref, 'dependabot/')
    needs:
      - test-and-build
    permissions:
      contents: write # Allow merging
      pull-requests: write
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: ${{ env.HARDEN_RUNNER_EGRESS_POLICY }}
          disable-sudo: true
          allowed-endpoints: >
            api.github.com:443
            github.com:443

      - name: Dependabot metadata
        uses: dependabot/fetch-metadata@08eff52bf64351f401fb50d4972fa95b9f2c2d1b # v2.4.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Approve a PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge the PR
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
