---
name: Test Coverage

on:
  workflow_run:
    workflows: ["Test & Build"]
    types:
      - completed
    branches:
      - main
  schedule:
    # UTC 21:00 -> JST 06:00
    - cron: "00 21 * * 6"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-coverage
  cancel-in-progress: false

env:
  GLOBAL_PYTHON_VERSION: ${{ vars.GLOBAL_PYTHON_VERSION }}
  GLOBAL_ALLOWED_ENDPOINTS: ${{ vars.GLOBAL_ALLOWED_ENDPOINTS }}
permissions:
  contents: read

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: >-
      github.event.workflow_run.conclusion == 'success' &&
      github.actor == github.repository_owner
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit
          disable-sudo: false
          disable-file-monitoring: false
          allowed-endpoints: ${{ env.GLOBAL_ALLOWED_ENDPOINTS }}
        timeout-minutes: 5

      - uses: actions/checkout@v4
        with:
          ref: develop

      - name: Setup Python and restore cache
        uses: ./.github/actions/setup-python
        with:
          python-version: ${{ env.GLOBAL_PYTHON_VERSION }}

      - name: Test coverage
        uses: ./.github/workflows/test-coverage.yml
        with:
          github-branch-name: develop
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
          codeclimate-token: ${{ secrets.CODECLIMATE_TEST_REPORTER_ID }}

  coverage-main:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: >-
      github.event.workflow_run.conclusion == 'success' &&
      github.actor == github.repository_owner
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit
          disable-sudo: false
          disable-file-monitoring: false
          allowed-endpoints: ${{ env.GLOBAL_ALLOWED_ENDPOINTS }}
        timeout-minutes: 5

      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Python and restore cache
        uses: ./.github/actions/setup-python
        with:
          python-version: ${{ env.GLOBAL_PYTHON_VERSION }}

      - name: Test coverage
        uses: ./.github/workflows/test-coverage.yml
        with:
          github-branch-name: main
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
          codeclimate-token: ${{ secrets.CODECLIMATE_TEST_REPORTER_ID }}
