---
name: Test and Build (on pull request)

on:
  pull_request:
    branches:
      - main
      - develop
    paths-ignore:
      - .cursor/**
      - .devcontainer/**
      - assets/**
      - docs/**
      - .gitignore
      - .pre-commit-config.yaml
      - .pyre_configuration
      - .yamllint.yml
      - "**.code-workspace"
      - codecov.yml
      - commitlint.config.js
      - LICENSE
      - README.md
    types:
      - opened
      - synchronize
      - reopened
      - edited

permissions:
  actions: read
  contents: read
  checks: write
  security-events: write
  id-token: write

env:
  GLOBAL_ALLOWED_ENDPOINTS: |
    api.github.com:443
    github.com:443
  GLOBAL_PYTHON_VERSION: ${{ vars.GLOBAL_PYTHON_VERSION }}

jobs:
  test-and-build:
    if: github.actor != 'dependabot[bot]'
    uses: ./.github/workflows/reusable-test-and-build.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    with:
      concurrency_group: pr-${{ github.workflow }}-${{ github.ref }}
      concurrency_cancel_in_progress: false
      workflow_summary_name: "Workflow summary [Test & Build (on pull request)]"

  test-e2e-benchmark:
    name: E2E Benchmark (${{ matrix.os }})
    permissions:
      contents: read
      pull-requests: write
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
        browser:
          - chromium
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit
          disable-sudo: true
          disable-file-monitoring: true
          allowed-endpoints: ${{ env.GLOBAL_ALLOWED_ENDPOINTS }}
        timeout-minutes: 5

      - name: Check out Git repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 1
        timeout-minutes: 3

      - name: Setup Python and restore cache
        uses: ./.github/actions/setup-python
        with:
          python-version: ${{ env.GLOBAL_PYTHON_VERSION }}
        timeout-minutes: 10

      - name: Run E2E Benchmark (Playwright)
        uses: ./.github/actions/test-python-playwright
        with:
          browser: ${{ matrix.browser }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          is-benchmark: true
        timeout-minutes: 30

  scorecards:
    name: OpenSSF Scorecards
    if: |
      github.event.pull_request.base.ref == 'main'
    permissions:
      contents: read
      actions: read
      security-events: write
      id-token: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit
          disable-sudo: true
          disable-file-monitoring: true
          allowed-endpoints: ${{ env.GLOBAL_ALLOWED_ENDPOINTS }}

      - name: "Checkout code"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: "Run analysis"
        uses: ossf/scorecard-action@f49aabe0b5af0936a0987cfb85d86b75731b0186 # v2.4.1
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true

  dependency-review:
    name: Dependency Review
    permissions:
      actions: read
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit
          disable-sudo: true
          disable-file-monitoring: true
          allowed-endpoints: ${{ env.GLOBAL_ALLOWED_ENDPOINTS }}

      - name: Check out Git repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 1

      - name: Dependency Review
        uses: actions/dependency-review-action@ce3cf9537a52e8119d91fd484ab5b8a807627bf8 # v4.6.0
        with:
          fail-on-severity: high
          comment-summary-in-pr: true
          # Pull Requestのコンテキストからbase_refとhead_refを取得
          base-ref: ${{ github.event.pull_request.base.ref }}
          head-ref: ${{ github.event.pull_request.head.ref }}

  pyre:
    permissions:
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit
          disable-sudo: true
          disable-file-monitoring: true
          allowed-endpoints: ${{ env.GLOBAL_ALLOWED_ENDPOINTS }}

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 1

      - name: Test Pyre
        uses: ./.github/actions/test-pyre
        with:
          python-version: ${{ env.GLOBAL_PYTHON_VERSION }}
        timeout-minutes: 10
        continue-on-error: true
