---
name: Test & Build (on push)

on:
  push:
    branches:
      - develop
    paths-ignore:
      - .cursor/**
      - .devcontainer/**
      - assets/**
      - README.md
      - .gitignore
      - .cz_config.js
      - .pre-commit-config.yaml
      - "**.code-workspace"

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  main:
    uses: ./.github/workflows/reusable-test-and-build.yml
    with:
      concurrency_group: push-${{ github.workflow }}-${{ github.ref }}
      concurrency_cancel_in_progress: true
      workflow_summary_name: "Workflow summary [Test & Build (on Push)]"

  get-npm-versions:
    outputs:
      main_version: ${{ steps.set-versions.outputs.main_version }}
      develop_version: ${{ steps.set-versions.outputs.develop_version }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit
          disable-sudo: true
          disable-file-monitoring: true

      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Get version from main
        id: get-main-ver
        uses: step-security/npm-get-version-action@v1

      - name: Checkout develop branch
        uses: actions/checkout@v4
        with:
          ref: develop
          fetch-depth: 0

      - name: Get version from develop
        id: get-dev-ver
        uses: step-security/npm-get-version-action@v1

      - name: Set versions output
        id: set-versions
        run: |
          echo "Main version: ${{ steps.get-main-ver.outputs.current-version }}"
          echo "Develop version: ${{ steps.get-dev-ver.outputs.current-version }}"
          echo "main_version=${{ steps.get-main-ver.outputs.current-version }}" >> "$GITHUB_OUTPUT"
          echo "develop_version=${{ steps.get-dev-ver.outputs.current-version }}" >> "$GITHUB_OUTPUT"

  create-pr-to-main:
    needs:
      - main
      - get-npm-versions
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit
          disable-sudo: true
          disable-file-monitoring: false

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create PR to main
        uses: ./.github/actions/create-pr-to-main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          develop_version: ${{ needs.get-npm-versions.outputs.develop_version }}
          main_version: ${{ needs.get-npm-versions.outputs.main_version }}
