---
name: Test Coverage

on:
  workflow_run:
    workflows: ["Test & Build"]
    types:
      - completed
    branches:
      - main
      - develop
  schedule:
    # UTC 21:00 -> JST 06:00
    - cron: "00 21 * * 6"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-coverage
  cancel-in-progress: false

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      python-version: 3.12
    if: >-
      github.event.workflow_run.conclusion == 'success' &&
      github.actor == github.repository_owner
    steps:
      - uses: actions/checkout@v4
        with:
          ref: develop

      - name: Setup Python and restore cache
        uses: ./.github/workflows/reusable-setup-pip.yml
        with:
          python-version: ${{ env.python-version }}
          os: ubuntu-latest

      - name: Run pytest
        run: |
          poetry run pytest --cov=app.py --cov=features --cov=i18n --cov=scripts --cov-report=xml --cov-report=term -n 2 --dist loadfile --durations=10 --cache-clear --maxfail=5 --verbose -k "not e2e"

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5.4.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  coverage-main:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      python-version: 3.12
    if: >-
      github.event.workflow_run.conclusion == 'success' &&
      github.actor == github.repository_owner
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Python and restore cache
        uses: ./.github/workflows/reusable-setup-pip.yml
        with:
          python-version: ${{ env.python-version }}
          os: ubuntu-latest

      - name: Run pytest (coverage without e2e)
        run: |
          poetry run pytest -n auto --cov=app.py --cov=features --cov=i18n --cov=scripts --cov-report=xml --cov-report=term --dist loadfile -k "not e2e" --benchmark-disable

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5.4.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Setup Code Climate
        uses: remarkablemark/setup-codeclimate@v2

      - name: Upload coverage reports to code climate
        run: |
          cc-test-reporter before-build

          cc-test-reporter after-build --exit-code $?
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_TEST_REPORTER_ID }}
