---
name: Test & Build on Pull request

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  test-and-build:
    uses: ./.github/workflows/reusable-test-and-build.yml
    with:
      concurrency_group: pr-${{ github.workflow }}-${{ github.ref }}
      concurrency_cancel_in_progress: false
